language: ruby
rvm:
- 2.2.3
script:
- rake travis
deploy:
  provider: heroku
  api_key:
    secure: BLfoww5Sl2wweyJ5bAcbLXEypVokKz1jkB8RIhxe3IF75nhXhJcNIVoH91AVejz8pRwFczEqerVobG9714AgUfPJjDQx5EEJDAPYq08pMRhfd/ebLJuPBgmiPtyDbLqTiC5SY4goy2JYsFqzFUsxAATpS9ycOi43FweQSNrCpu73u3rseqEmhkonwd+huunNLLl0P8+oxpGDuBGhTDg0/WZ/VE9Jr+it+0XR7h54u7ZUEKjIeK+1WfqthwlZ9h/lzpM3DBZ8kLwUSm8vqloxCxa0d0FKk4dXIOhlJAu39qb/yG6IJzCfEt2eNpd+C0IkLXF0OjCU+Xm6g8zg27E2pyQSG8F4IYRY612Neow8eGPM4dMduW5R262lBKTCas5+XRXO9fSu0MasidlIGHr5qdJYtcKEfwyarCPc+r06bVUKpDsb1bQThDKZ09u2mCz19i0LkUEF8ScIpsfUJMbBmDahyCQyvjT4pA111aE8tnwSaRMyMTBKbwtYzD5YlGZtgu7Oi3gxyFyZfSR05ALlAoP3eV7V1xhAjYkniHGKh/564B22TMITAEqgnavAu6ilGcpVBXn+KrYRztYSGkgmtVdPYSetM8Hw7OvCcg4MG1vd9k1Z3FlJVYyohhElhfx3fBggPCA0NsxbwHvxT1SvJcvOJuakYOTD7MlGeR6N9ms=
  app: diversity-poll
  run:
    - "rake db:setup"
    - "rake db:populate"
